In [ ]:
# Python Program illustrating
# numpy.dot() method

import numpy as geek

# Scalars
product = geek.dot(5, 4)
print("Dot Product of scalar values : ", product)

# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j

product = geek.dot(vector_a, vector_b)
print("Dot Product : ", product)


In [ ]:
# Dot Product of scalar values  :  20
# Dot Product  :  (-7+22j)

# How Code1 works ? 

# vector_a = 2 + 3j 
# vector_b = 4 + 5j

# now dot product 

# = 2(4 + 5j) + 3j(4 +5j) 
# = 8 + 10j + 12j - 15 
# = -7 + 22j

In [1]:
# Python Program illustrating
# numpy.dot() method

import numpy as geek

# 1D array
vector_a = geek.array([[1, 4], [5, 6]])
vector_b = geek.array([[2, 4], [5, 2]])

product = geek.dot(vector_a, vector_b)
print("Dot Product : \n", product)

product = geek.dot(vector_b, vector_a)
print("\nDot Product : \n", product)

""" 
Code 2 : as normal matrix multiplication
"""


Dot Product : 
 [[22 12]
 [40 32]]

Dot Product : 
 [[22 32]
 [15 32]]


' \nCode 2 : as normal matrix multiplication\n'

In [ ]:
# Dot Product  : 
#  [[22 12]
#  [40 32]]

# Dot Product  : 
#  [[22 32]
#  [15 32]]